[package]
authors = ["Lokathor <zefria@gmail.com>"]
description = "A discord bot to roll RPG dice rolls."
keywords = ["discord", "dice"]
license = "0BSD"
name = "dice-bot"
publish = false
readme = "README.md"
repository = "https://github.com/Lokathor/dice-bot-rs"
version = "0.4.3"

[dependencies]
meval = "0.2.0"
randomize = "1.0"
serenity = "0.5"

[profile]

[profile.release]
codegen-units = 1
lto = true
