[package]
name = "dice-bot"
version = "0.4.3"
authors = ["Lokathor <zefria@gmail.com>"]
repository = "https://github.com/Lokathor/dice-bot-rs"
readme = "README.md"
keywords = ["discord","dice"]
description = "A discord bot to roll RPG dice rolls."
license = "0BSD"
publish = false

[dependencies]
serenity = "0.5"
randomize = "1.0"

[profile.release]
lto = true
codegen-units = 1
