[package]
name = "dice-bot"
version = "0.5.0-alpha1"
authors = ["Lokathor <zefria@gmail.com>"]
repository = "https://github.com/Lokathor/dice-bot-rs"
readme = "README.md"
keywords = ["discord","dice"]
description = "A discord bot to roll RPG dice rolls."
license = "0BSD"
publish = false
edition = "2018"

[dependencies]
serenity = "0.6"
randomize = "3.0.0-rc.3"

[profile.release]
lto = true
codegen-units = 1
