error_on_line_overflow = false
fn_args_density = "Compressed"
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
use_try_shorthand = true
write_mode = "Overwrite"
tab_spaces = 2
max_width = 150
color = "Never"
